Update scrolls.xml
BetaMasaheft/guidelines pull request #120
Opened 2021-02-10 14:55 UTC by DariaElagina

see [https://github.com/BetaMasaheft/Documentation/issues/1379#event-4313735152](url)

2021-02-10 15:31 UTC, DenisNosnitsin1970 approved these changes

2021-02-10 16:29 UTC, thea-m requested changes
Thank you :)

2021-02-10 16:29 UTC, thea-m commented on pages/scrolls.xml
>                  <p>We treat Scrolls in the same way as we do with <ref target="manuscripts">Manuscripts</ref> and any other written artefacts,
I know it is an old sentence, but let's take the opportunity to make it correct:
"We treat scrolls in the same way as `<ref target="manuscripts">codices</ref>`"

2021-02-10 16:29 UTC, thea-m commented on pages/scrolls.xml
> +                    and only add in <gi>objectDesc</gi> the value Scroll for <att>form</att> However,
I think . after `</att>`  is missing

2021-02-10 16:29 UTC, thea-m commented on pages/scrolls.xml
> +                  of other features. For example:</p>
no of?

2021-02-11 11:54 UTC, eu-genia approved these changes

2021-02-11 11:54 UTC, merged